baseURL = 'https://filippocristofoli.it/'
languageCode = 'it-it'
title = 'Filippo Cristofoli | Nutrizionista'
theme = 'roxo-hugo'
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Chi sono"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Servizi"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Contattami"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/fc-logo-transparent-new.svg"
  logo_footer = "images/fc-logo-new.svg"
  favicon_icon = "images/fc-favicon-color-new.svg"
  favicon_shortcut_icon = "images/fc-favicon-color.svg"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Filippo Cristofoli | Nutrizionista. INSERISCI UNA DESCRIZIONE."
  author = "Matteo Marjanovic"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nome"
    placeholder_last_name         = "Cognome"
    placeholder_email             = "Email"
    placeholder_project_type      = "Servizio"
    placeholder_about_the_project = "Dettagli"
    send_message                  = "Invia"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
    [[params.contactForm.projectType]]
      value = "all"
      title  = "Altro"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/food.jpeg"
    heading               = "Biologo Nutrizionista a Villafranca di Verona"
    tagline               = 'IL BENESSERE OLISTICO INIZIA A TAVOLA'
    primary_button        = "I miei Servizi"
    primary_button_url    = "portfolio"
    secondary_button      = "Contattami"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "I MIEI SERVIZI"
    subtitle  = "Alcuni dei miei servizi:"
    view_project = "Scopri di più"
    more_works = "CARICA ALTRI"
    scroll_down = "Vai ai servizi"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Tutti i miei servizi"
    primary_button_url  = "portfolio"
    secondary_button    = "Contattami"
    secondary_button_url = "contact"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informazioni"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      piva    = "4854489304298"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Chi sono"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Servizi"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contatti"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "Torna all'inizio"
