baseURL = 'https://filippocristofoli.it/'
languageCode = 'it-it'
title = 'Filippo Cristofoli | Nutrizionista'
theme = 'my-roxo-hugo'
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Chi sono"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Servizi"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contattami"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo-pippo-removebg.png"
  logo_footer = "images/logo-pippo.png"
  favicon_icon = "images/icona-pippo.png"
  favicon_shortcut_icon = "images/icona-pippo.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Filippo Cristofoli, Biologo Nutrizionista a Verona, offre consulenza a Povegliano Veronese e Villafranca di Verona, oltre ad altre regioni italiane. Co-autore nella collana Il Conviviale, con focus sull'alimentazione sana e bilanciata."
  author = "Matteo Marjanovic"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/WopbCdP"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nome"
    placeholder_last_name         = "Cognome"
    placeholder_email             = "Email"
    placeholder_project_type      = "Servizio"
    placeholder_about_the_project = "Dettagli"
    send_message                  = "Invia"

    [[params.contactForm.projectType]]
      value = "prima-visita"
      title  = "Prima Visita"
    [[params.contactForm.projectType]]
      value = "controllo"
      title  = "Visita di Controllo"
    [[params.contactForm.projectType]]
      value = "all"
      title  = "Altro"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/food.jpeg"
    heading               = "Biologo Nutrizionista a Villafranca di Verona"
    tagline               = 'IL BENESSERE OLISTICO INIZIA A TAVOLA'
    primary_button        = "I miei Servizi"
    primary_button_url    = "portfolio"
    secondary_button      = "Contattami"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "I MIEI SERVIZI"
    subtitle  = "Alcuni dei miei servizi:"
    view_project = "Scopri di più"
    more_works = "CARICA ALTRI"
    scroll_down = "Vai ai servizi"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LAVORIAMO INSIEME"
    primary_button      = "I miei servizi"
    primary_button_url  = "portfolio"
    secondary_button    = "Contattami"
    secondary_button_url = "contact"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informazioni"
      address = "Riceve su appuntamento presso lo studio in<br />Via Matteotti 1, Povegliano Veronese, 37064<br />"
      piva    = "05025400234"
      phone   = "376 236 8261"
      email   = "nutrizionista.cristofolifilippo@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Chi sono"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Servizi"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contatti"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/filippo-cristofoli-b63277233/"
      # Footer Service
      [params.footer.service]
        title       = "Chi sono:"
        description = "Filippo Cristofoli è un Biologo Nutrizionista. Offre consulenza a Povegliano Veronese e Villafranca di Verona. Co-autore nella collana Il Conviviale, con focus sull'alimentazione sana e bilanciata."
      [params.footer.back_to_top]
        description = "Torna all'inizio"
